### PR TITLE
Remove unnecessary locking.

### PR DESCRIPTION
**Pull request by eirrgang**
Two mutexes were in place to provide thread safety in the call-back,
but the thread safety should be guaranteed by the gmxapi framework, so
these were an unnecessary performance expense.

### CODE REVIEW

**Comment by eirrgang** [comment]
Unfortunately, removing an enclosing block creates a lot of diff noise. If reviewing on GitHub, I suggest switching from "split" view to "unified" view to see if that makes it easier to look at.

**Review by jmhays — COMMENTED** [review]
How do you know the locking is unnecessary? Are there checks you can put in place to make sure this is the case?

**Comment by eirrgang** [comment]
The locking is unnecessary because thread safety is managed one level higher in the call stack. The framework that calls this only calls it on the master rank of the domain decomposition. I want to make this more explicit as the callback API matures, but I'm not sure how best to do that. e.g. whether to have callbacks with different names if they _should_ get called on all ranks (in which case they could currently just use the calculate function, though that is not a long-term solution) or, more likely, either some sort of "type trait" that the developer can set in their class or, perhaps better, a dispatch tag that can be used in the call signature.

E.g.

    callback(vec r1, vec r0, double t, gmxapi::call_policy::single_thread()) {};

This would be incompatible with gmxapi 0.0.4, though, and the sample_restraint has not been bumped to 0.0.5 development yet. I think this PR will improve the performance under 0.0.4, but I don't have numbers for it. If we put it off to 0.0.5, that's fine, too, I suppose, and I could make it align with a change that adds such guarantees on the gromacs-gmxapi side.

**Comment by eirrgang** [comment]
If you want to confirm or refute that the locking is unnecessary before approving, that would be great. If you would like to do so, but would rather do it in the context of 0.0.5 development, that would be fine, too.

**Pull request merged**
